name: expenses_managment_app_provider
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  camera: ^0.10.5+5
  connectivity: ^3.0.6
  dio: ^5.3.3
  firebase_analytics: ^10.7.0
  firebase_auth: ^4.14.0
  firebase_core: ^2.21.0
  firebase_database: ^10.3.3
  firebase_dynamic_links: ^5.4.4
  firebase_performance: ^0.9.3+4
  firebase_storage: ^11.5.0
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.2
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  http: ^1.1.0
  http_interceptor: ^2.0.0-beta.7
  image_picker: ^1.0.4
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  # photo_manager: ^2.8.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  sidebarx: ^0.16.3
  sqflite: ^2.3.0
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fund-agreement-for-startup.png
    - assets/facebook.png
    - assets/google.png
    - assets/user.png
