name: expenses_managment_app_provider
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.3
  firebase_core: ^2.21.0
  firebase_database: ^10.3.3
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.1.0
  http_interceptor: ^2.0.0-beta.7
  intl: ^0.18.1
  provider: ^6.0.5
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
