// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmNOTdRsRGnCjgEg6FmMumZzPnjDGxQ1A',
    appId: '1:296448364006:web:6aefdd282c86382bbeda27',
    messagingSenderId: '296448364006',
    projectId: 'providerrest',
    authDomain: 'providerrest.firebaseapp.com',
    databaseURL: 'https://providerrest-default-rtdb.firebaseio.com',
    storageBucket: 'providerrest.appspot.com',
    measurementId: 'G-YNX16BDZVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzCwL7Ey0VCKFqnWHyiJP8tUa6Un5rzvw',
    appId: '1:296448364006:android:3236308341b98d02beda27',
    messagingSenderId: '296448364006',
    projectId: 'providerrest',
    databaseURL: 'https://providerrest-default-rtdb.firebaseio.com',
    storageBucket: 'providerrest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOFKIKbPgdjEEzpr8Uxb1PIjlqXC0l1q8',
    appId: '1:296448364006:ios:19367ce8916e0b58beda27',
    messagingSenderId: '296448364006',
    projectId: 'providerrest',
    databaseURL: 'https://providerrest-default-rtdb.firebaseio.com',
    storageBucket: 'providerrest.appspot.com',
    androidClientId: '296448364006-ked98giprblrnnhovr0c06sat4j7trs6.apps.googleusercontent.com',
    iosClientId: '296448364006-3r8tn0967u6ved27vl69a8ikedknu8v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensesManagmentAppProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOFKIKbPgdjEEzpr8Uxb1PIjlqXC0l1q8',
    appId: '1:296448364006:ios:767b2f62164a7db7beda27',
    messagingSenderId: '296448364006',
    projectId: 'providerrest',
    databaseURL: 'https://providerrest-default-rtdb.firebaseio.com',
    storageBucket: 'providerrest.appspot.com',
    androidClientId: '296448364006-ked98giprblrnnhovr0c06sat4j7trs6.apps.googleusercontent.com',
    iosClientId: '296448364006-5p85g96f4j2jm962vj116ap6hfsj4fn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensesManagmentAppProvider.RunnerTests',
  );
}
